class BoardPiece{
.... Getters ....

.... Setters ....
.... Methods ....

____ Private Data ____
string label
string color
ClassObject surprise <-- (supposed to be whatever surprise is awaiting on the tile)
int piece_in_place (true/false)


}