@startuml

class Board{
.... Methods ....
 + __init__()
 + update(self, pieces: list[ChessPiece])
 + get_piece(self, row: int, col: int): Optional[ChessPiece]
 + is_empty(self, row: int, col: int): bool
 + get_tile(self, row: int, col: int): BoardPiece

.... Public Data ....
 + int rows
 + int cols
 + list[list[Optional[ChessPiece]]] grid
 + list[list[BoardPiece]] board_state
}

class BoardPiece{
.... Getters ....
+ get_label(self): str
+ get_color(self): str
+ get_surprise(self): obj
+ is_piece_in_place(self): bool

.... Setters ....
 + set_label(self, label: str)
 + set_color(self, color: str)
 + set_surprise(self, surprise: obj)
 + set_piece_in_place(self, in_place: bool)

.... Methods ....
 + __init__()

____ Private Data ____
 - string label
 - string color
 - object surprise
 - bool piece_in_place

}

Board <|--- BoardPiece

@enduml